version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkinsmoviesphere
    user: root
    ports:
      - "5050:8080"
      - "50000:50000"
    volumes:
      - jenkins_moviesphere:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc_configs/casc.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/casc.yml
    networks:
      - jenkins_moviesphere
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # restart: unless-stopped

  terraform-agent:
    build:
      context: ./agent-terraform
    image: terraform-agent:latest
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=terraform-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_PORT=50000
      - JENKINS_PROTOCOLS=JNLP4-connect
      - JENKINS_INSTANCE_IDENTITY=${JENKINS_INSTANCE_IDENTITY}
    networks:
      - jenkins_moviesphere
    depends_on:
      jenkins:
        condition: service_healthy

volumes:
  jenkins_moviesphere:
  terraform_data:

networks:
  jenkins_moviesphere:
    driver: bridge