version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkinsmoviesphere
    ports:
      - "5040:8080"
      - "50040:50000"
    volumes:
      - jenkins_moviesphere:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_moviesphere
    restart: unless-stopped

  terraform-agent:
    build:
      context: ./agent-terraform
    networks:
      - jenkins_moviesphere
    restart: unless-stopped

volumes:
  jenkins_moviesphere:

networks:
  jenkins_moviesphere:
    driver: bridge